# Generated by Django 5.0.6 on 2024-07-10 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_delivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("paypal", "PayPal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("card_number", models.CharField(blank=True, max_length=16, null=True)),
                ("card_expiry", models.CharField(blank=True, max_length=5, null=True)),
                ("card_cvv", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "paypal_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.delivery"
                    ),
                ),
            ],
        ),
    ]
